version: '3'

services:
  tusd:
    image: tusproject/tusd
    command: tusd --hooks-dir /hooks --unroutable true --broker amqp://guest:guest@rabbitmq:5672/ --base-path /files --upload-dir /data
    volumes:
      - ./hooks:/hooks
    ports:
      - 1080:1080
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
