version: '3'

services:
  db:
    container_name: volweb_postgresdb
    image: postgres:14.1
    restart: always
    env_file:
      - ./secret/volweb.env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    container_name: volweb_django
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: >
      gunicorn VolWeb.wsgi:application --bind 0.0.0.0:8000 --workers=4  --timeout 120
    env_file:
      - ./secret/volweb.env
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - ./cases:/home/app/web/Cases/
      - ./cases/Results/:/home/app/web/Cases/Results
      - ./cases/files/:/home/app/web/Cases/files
      - staticfiles:/home/app/web/staticfiles
      - symbols:/home/app/web/symbols/uploads

  nginx:
    container_name: volweb_nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/ssl/:/etc/nginx/certs/
      - staticfiles:/home/app/web/staticfiles
    depends_on:
      - web

  rabbitmq3:
    container_name: volweb_rabbitmq
    image: rabbitmq:3.9.13
    ports:
      - "5672:5672"
    env_file:
      - ./secret/volweb.env
  worker:
    container_name: volweb_worker
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - secret/volweb.env
    command: celery -A investigations worker -l INFO
    depends_on:
      - rabbitmq3
      - db
    volumes:
      - ./cases:/home/app/web/Cases/
      - ./cases/Results/:/home/app/web/Cases/Results
      - ./cases/files/:/home/app/web/Cases/files
      - staticfiles:/home/app/web/staticfiles
      - symbols:/home/app/web/symbols/uploads
volumes:
  staticfiles:
  symbols:
